export type EconomicIndicatorSource = "world-bank" | "imf-weo" | "imf-debt";
export type EconomicScale = "sequential" | "diverging";
export type EconomicIndicatorGroup =
  | "Economic Overview"
  | "External Economy"
  | "Fiscal Health"
  | "Investment & Savings"
  | "Financial Conditions"
  | "Financial System"
  | "Development & Demographics";

export type EconomicIndicator = {
  id: string;
  code: string;
  label: string;
  shortLabel?: string;
  group: EconomicIndicatorGroup;
  source: EconomicIndicatorSource;
  sourceLabel: string;
  unit?: string;
  description: string;
  scale: EconomicScale;
  profileIndicatorCode?: string;
};

export const ECONOMIC_INDICATORS: EconomicIndicator[] = [
  // Economic Overview
  {
    id: "population",
    code: "SP.POP.TOTL",
    label: "Population",
    group: "Economic Overview",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    description: "Total resident population.",
    scale: "sequential",
    profileIndicatorCode: "SP.POP.TOTL",
  },
  {
    id: "gdp-current-usd",
    code: "NY.GDP.MKTP.CD",
    label: "GDP (current US$)",
    group: "Economic Overview",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "US$",
    description: "Size of the economy at current market prices.",
    scale: "sequential",
    profileIndicatorCode: "NY.GDP.MKTP.CD",
  },
  {
    id: "gdp-growth",
    code: "NY.GDP.MKTP.KD.ZG",
    label: "Real GDP Growth",
    group: "Economic Overview",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "%",
    description: "Annual growth rate of real GDP after adjusting for inflation.",
    scale: "diverging",
    profileIndicatorCode: "NY.GDP.MKTP.KD.ZG",
  },
  {
    id: "gdp-per-capita",
    code: "NY.GDP.PCAP.CD",
    label: "GDP per Capita",
    group: "Economic Overview",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "US$",
    description: "Economic output per person at current US dollar prices.",
    scale: "sequential",
    profileIndicatorCode: "NY.GDP.PCAP.CD",
  },
  {
    id: "inflation",
    code: "FP.CPI.TOTL.ZG",
    label: "Inflation",
    group: "Economic Overview",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "%",
    description: "Annual change in consumer prices.",
    scale: "diverging",
    profileIndicatorCode: "FP.CPI.TOTL.ZG",
  },
  {
    id: "unemployment",
    code: "SL.UEM.TOTL.ZS",
    label: "Unemployment",
    group: "Economic Overview",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "%",
    description: "Share of the labour force without work but available for and seeking employment.",
    scale: "sequential",
    profileIndicatorCode: "SL.UEM.TOTL.ZS",
  },

  // External Economy
  {
    id: "current-account-gdp",
    code: "BN.CAB.XOKA.GD.ZS",
    label: "Current Account Balance",
    group: "External Economy",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "% of GDP",
    description: "Current account balance relative to the size of the economy.",
    scale: "diverging",
    profileIndicatorCode: "BN.CAB.XOKA.GD.ZS",
  },
  {
    id: "trade-gdp",
    code: "NE.TRD.GNFS.ZS",
    label: "Trade",
    group: "External Economy",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "% of GDP",
    description: "Exports plus imports of goods and services as a share of GDP.",
    scale: "sequential",
    profileIndicatorCode: "NE.TRD.GNFS.ZS",
  },
  {
    id: "exports-gdp",
    code: "NE.EXP.GNFS.ZS",
    label: "Exports",
    group: "External Economy",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "% of GDP",
    description: "Exports of goods and services as a share of GDP.",
    scale: "sequential",
    profileIndicatorCode: "NE.EXP.GNFS.ZS",
  },
  {
    id: "imports-gdp",
    code: "NE.IMP.GNFS.ZS",
    label: "Imports",
    group: "External Economy",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "% of GDP",
    description: "Imports of goods and services as a share of GDP.",
    scale: "sequential",
    profileIndicatorCode: "NE.IMP.GNFS.ZS",
  },
  {
    id: "fdi-inflows-gdp",
    code: "BX.KLT.DINV.WD.GD.ZS",
    label: "FDI Net Inflows",
    group: "External Economy",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "% of GDP",
    description: "Net foreign direct investment inflows relative to GDP.",
    scale: "diverging",
    profileIndicatorCode: "BX.KLT.DINV.WD.GD.ZS",
  },
  {
    id: "foreign-reserves",
    code: "FI.RES.TOTL.CD",
    label: "Foreign Exchange Reserves",
    group: "External Economy",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "US$",
    description: "Total reserves including gold, measured in current US dollars.",
    scale: "sequential",
    profileIndicatorCode: "FI.RES.TOTL.CD",
  },
  {
    id: "reserves-months-imports",
    code: "FI.RES.TOTL.MO",
    label: "Reserves in Months of Imports",
    group: "External Economy",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "months",
    description: "How many months of imports can be covered by international reserves.",
    scale: "sequential",
    profileIndicatorCode: "FI.RES.TOTL.MO",
  },

  // Fiscal Health
  {
    id: "government-debt-gdp",
    code: "DEBT",
    label: "Government Debt",
    group: "Fiscal Health",
    source: "imf-debt",
    sourceLabel: "IMF WEO",
    unit: "% of GDP",
    description: "General government gross debt relative to GDP.",
    scale: "sequential",
  },
  {
    id: "fiscal-balance-gdp",
    code: "GGXCNL_NGDP",
    label: "Fiscal Balance",
    group: "Fiscal Health",
    source: "imf-weo",
    sourceLabel: "IMF WEO",
    unit: "% of GDP",
    description: "General government net lending or borrowing relative to GDP.",
    scale: "diverging",
  },
  {
    id: "primary-balance-gdp",
    code: "GGXONLB_NGDP",
    label: "Primary Balance",
    group: "Fiscal Health",
    source: "imf-weo",
    sourceLabel: "IMF WEO",
    unit: "% of GDP",
    description: "Primary net lending or borrowing of general government relative to GDP.",
    scale: "diverging",
  },
  {
    id: "government-revenue-gdp",
    code: "GGR_NGDP",
    label: "Government Revenue",
    group: "Fiscal Health",
    source: "imf-weo",
    sourceLabel: "IMF WEO",
    unit: "% of GDP",
    description: "General government revenue relative to GDP.",
    scale: "sequential",
  },
  {
    id: "government-expenditure-gdp",
    code: "GGX_NGDP",
    label: "Government Expenditure",
    group: "Fiscal Health",
    source: "imf-weo",
    sourceLabel: "IMF WEO",
    unit: "% of GDP",
    description: "General government expenditure relative to GDP.",
    scale: "sequential",
  },
  {
    id: "tax-revenue-gdp",
    code: "GC.TAX.TOTL.GD.ZS",
    label: "Tax Revenue",
    group: "Fiscal Health",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "% of GDP",
    description: "Tax revenue collected by government as a share of GDP.",
    scale: "sequential",
    profileIndicatorCode: "GC.TAX.TOTL.GD.ZS",
  },
  {
    id: "interest-payments-revenue",
    code: "GC.XPN.INTP.RV.ZS",
    label: "Interest Payments",
    group: "Fiscal Health",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "% of revenue",
    description: "Government interest payments as a share of government revenue.",
    scale: "sequential",
    profileIndicatorCode: "GC.XPN.INTP.RV.ZS",
  },

  // Investment & Savings
  {
    id: "investment-gdp",
    code: "NID_NGDP",
    label: "Investment",
    group: "Investment & Savings",
    source: "imf-weo",
    sourceLabel: "IMF WEO",
    unit: "% of GDP",
    description: "Total investment relative to GDP in the IMF WEO framework.",
    scale: "sequential",
    profileIndicatorCode: "NE.GDI.TOTL.ZS",
  },
  {
    id: "gross-capital-formation-gdp",
    code: "NE.GDI.TOTL.ZS",
    label: "Gross Capital Formation",
    group: "Investment & Savings",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "% of GDP",
    description: "Investment in fixed assets plus changes in inventories as a share of GDP.",
    scale: "sequential",
    profileIndicatorCode: "NE.GDI.TOTL.ZS",
  },
  {
    id: "national-savings-gdp",
    code: "NGSD_NGDP",
    label: "National Savings",
    group: "Investment & Savings",
    source: "imf-weo",
    sourceLabel: "IMF WEO",
    unit: "% of GDP",
    description: "Gross national savings relative to GDP in the IMF WEO framework.",
    scale: "sequential",
    profileIndicatorCode: "NY.GNS.ICTR.ZS",
  },
  {
    id: "gross-savings-gdp",
    code: "NY.GNS.ICTR.ZS",
    label: "Gross Savings",
    group: "Investment & Savings",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "% of GDP",
    description: "Gross savings as a share of GDP.",
    scale: "sequential",
    profileIndicatorCode: "NY.GNS.ICTR.ZS",
  },

  // Financial Conditions
  {
    id: "lending-rate",
    code: "FR.INR.LEND",
    label: "Lending Interest Rate",
    group: "Financial Conditions",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "%",
    description: "Bank lending rate that usually meets short- and medium-term financing needs.",
    scale: "sequential",
    profileIndicatorCode: "FR.INR.LEND",
  },
  {
    id: "deposit-rate",
    code: "FR.INR.DPST",
    label: "Deposit Interest Rate",
    group: "Financial Conditions",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "%",
    description: "Rate paid by commercial or similar banks for demand, time, or savings deposits.",
    scale: "sequential",
    profileIndicatorCode: "FR.INR.DPST",
  },
  {
    id: "real-interest-rate",
    code: "FR.INR.RINR",
    label: "Real Interest Rate",
    group: "Financial Conditions",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "%",
    description: "Lending interest rate adjusted for inflation as measured by the GDP deflator.",
    scale: "diverging",
    profileIndicatorCode: "FR.INR.RINR",
  },
  {
    id: "broad-money-gdp",
    code: "FM.LBL.BMNY.GD.ZS",
    label: "Broad Money",
    group: "Financial Conditions",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "% of GDP",
    description: "Broad money supply relative to GDP.",
    scale: "sequential",
    profileIndicatorCode: "FM.LBL.BMNY.GD.ZS",
  },
  {
    id: "broad-money-growth",
    code: "FM.LBL.BMNY.ZG",
    label: "Broad Money Growth",
    group: "Financial Conditions",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "%",
    description: "Annual growth rate of broad money.",
    scale: "diverging",
    profileIndicatorCode: "FM.LBL.BMNY.ZG",
  },
  {
    id: "private-credit-gdp",
    code: "FS.AST.PRVT.GD.ZS",
    label: "Private Sector Credit",
    group: "Financial Conditions",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "% of GDP",
    description: "Domestic credit provided to the private sector by banks relative to GDP.",
    scale: "sequential",
    profileIndicatorCode: "FS.AST.PRVT.GD.ZS",
  },

  // Financial System
  {
    id: "bank-npl-ratio",
    code: "FB.AST.NPER.ZS",
    label: "Bank Nonperforming Loans",
    group: "Financial System",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "% of gross loans",
    description: "Nonperforming bank loans as a share of total gross loans.",
    scale: "sequential",
    profileIndicatorCode: "FB.AST.NPER.ZS",
  },
  {
    id: "bank-capital-assets",
    code: "FB.BNK.CAPA.ZS",
    label: "Bank Capital to Assets",
    group: "Financial System",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "%",
    description: "Bank regulatory capital relative to total assets.",
    scale: "sequential",
    profileIndicatorCode: "FB.BNK.CAPA.ZS",
  },
  {
    id: "market-cap-gdp",
    code: "CM.MKT.LCAP.GD.ZS",
    label: "Stock Market Capitalization",
    group: "Financial System",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "% of GDP",
    description: "Market capitalization of listed domestic companies relative to GDP.",
    scale: "sequential",
    profileIndicatorCode: "CM.MKT.LCAP.GD.ZS",
  },
  {
    id: "listed-companies",
    code: "CM.MKT.LDOM.NO",
    label: "Listed Domestic Companies",
    group: "Financial System",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "count",
    description: "Number of domestically incorporated companies listed on domestic stock exchanges.",
    scale: "sequential",
    profileIndicatorCode: "CM.MKT.LDOM.NO",
  },
  {
    id: "stocks-traded-gdp",
    code: "CM.MKT.TRAD.GD.ZS",
    label: "Stocks Traded",
    group: "Financial System",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "% of GDP",
    description: "Total value of shares traded relative to GDP.",
    scale: "sequential",
    profileIndicatorCode: "CM.MKT.TRAD.GD.ZS",
  },
  {
    id: "stock-turnover",
    code: "CM.MKT.TRNR",
    label: "Stock Market Turnover",
    group: "Financial System",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "%",
    description: "Value of shares traded relative to average market capitalization.",
    scale: "sequential",
    profileIndicatorCode: "CM.MKT.TRNR",
  },

  // Development & Demographics
  {
    id: "population-growth",
    code: "SP.POP.GROW",
    label: "Population Growth",
    group: "Development & Demographics",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "%",
    description: "Annual population growth rate.",
    scale: "diverging",
    profileIndicatorCode: "SP.POP.GROW",
  },
  {
    id: "life-expectancy",
    code: "SP.DYN.LE00.IN",
    label: "Life Expectancy",
    group: "Development & Demographics",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "years",
    description: "Life expectancy at birth.",
    scale: "sequential",
    profileIndicatorCode: "SP.DYN.LE00.IN",
  },
  {
    id: "urban-population",
    code: "SP.URB.TOTL.IN.ZS",
    label: "Urban Population",
    group: "Development & Demographics",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "%",
    description: "Share of population living in urban areas.",
    scale: "sequential",
    profileIndicatorCode: "SP.URB.TOTL.IN.ZS",
  },
  {
    id: "electricity-access",
    code: "EG.ELC.ACCS.ZS",
    label: "Access to Electricity",
    group: "Development & Demographics",
    source: "world-bank",
    sourceLabel: "World Bank WDI",
    unit: "%",
    description: "Share of the population with access to electricity.",
    scale: "sequential",
    profileIndicatorCode: "EG.ELC.ACCS.ZS",
  },
];

export const ECONOMIC_INDICATOR_GROUPS: EconomicIndicatorGroup[] = [
  "Economic Overview",
  "External Economy",
  "Fiscal Health",
  "Investment & Savings",
  "Financial Conditions",
  "Financial System",
  "Development & Demographics",
];

export const DEFAULT_ECONOMIC_INDICATOR_ID = "population";

export function getEconomicIndicator(idOrCode: string | null | undefined) {
  const value = String(idOrCode ?? "").trim();
  return (
    ECONOMIC_INDICATORS.find((item) => item.id === value) ??
    ECONOMIC_INDICATORS.find((item) => item.code === value) ??
    ECONOMIC_INDICATORS.find((item) => item.id === DEFAULT_ECONOMIC_INDICATOR_ID)!
  );
}